I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 836, in script
    show jade sad l at center
Exception: Image 'jade sad' does not accept attributes 'l'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 836, in script
    show jade sad l at center
  File "C:\Users\PC\Documents\renpy-8.3.7-sdk\renpy\ast.py", line 1124, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\PC\Documents\renpy-8.3.7-sdk\renpy\ast.py", line 1087, in show_imspec
    renpy.config.show(name,
  File "C:\Users\PC\Documents\renpy-8.3.7-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\PC\Documents\renpy-8.3.7-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\PC\Documents\renpy-8.3.7-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\PC\Documents\renpy-8.3.7-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'jade sad' does not accept attributes 'l'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
ACHJam 1.0
Tue Apr 15 15:18:33 2025
